import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Users, CalendarDays, Trophy, BarChart3, GraduationCap, BadgeCheck, HeartHandshake, PackageOpen, LockKeyhole, Puzzle, Shield, MessageCircle, Globe2, ChevronRight, Menu, X, Radio, Swords, Activity, Ban, Flag, TrendingUp } from 'lucide-react';
import { SITE_CONFIG } from './config/siteConfig';
import './styles.css';

const LANG_KEY = SITE_CONFIG.languageStorageKey || 'r6cuba-language';
const LANGUAGES = [
  { code: 'es', short: 'ES', name: 'Español', flag: '🇨🇺' },
  { code: 'en', short: 'EN', name: 'English', flag: '🇺🇸' },
  { code: 'fr', short: 'FR', name: 'Français', flag: '🇫🇷' },
  { code: 'de', short: 'DE', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', short: '中文', name: '中文', flag: '🇨🇳' },
  { code: 'ja', short: '日本語', name: '日本語', flag: '🇯🇵' }
];
const IM = '/assets/backgrounds/';

const DATA = {
  es: {
    nav: ['Inicio','Comunidad','Eventos','Competitivo','Estadísticas','Coaches','Partners','Colaboradores','Próximamente'],
    badge: 'Centro operativo comunitario', title: ['RAINBOW','SIX','CUBA'], subtitle: 'La comunidad cubana de Rainbow Six Siege.',
    body: 'Coordinamos jugadores, equipos, coaches y colaboradores dentro y fuera de Cuba para competir, organizarnos y crecer como una comunidad seria.',
    join:'Únete al Discord', explore:'Explorar comunidad', view:'Ver más', platform:'Community Platform', companion:'Companion Extension',
    modules: {
      community:['Comunidad','Encuentra jugadores, equipos y miembros activos de Rainbow Six dentro y fuera de Cuba.'],
      events:['Eventos','Torneos, scrims, cups y actividades organizadas para la comunidad.'],
      competitive:['Competitivo','Equipos, ligas, rankings y todo lo relacionado con el competitivo cubano.'],
      statistics:['Estadísticas','Estadísticas públicas, leaderboards, análisis y seguimiento de jugadores.'],
      coaches:['Coaches Verificados','Mejora tu juego con coaches verificados por la comunidad.'],
      partners:['Partners Verificados','Organizaciones y comunidades que apoyan el crecimiento de Rainbow Six en Cuba.'],
      collaborators:['Colaboradores','Personas que trabajan detrás de escena para hacer crecer nuestra comunidad.'],
      incoming:['Próximamente','Nuevos proyectos, herramientas y recursos en camino.'],
      privacy:['Privacidad','Datos protegidos, transparencia y reglas claras para todos.'],
      companion:['Companion Extension','La extensión oficial de Rainbow Six CUBA. Conecta, analiza y lleva tu experiencia al siguiente nivel.']
    },
    values:[['Comunidad activa','Miles de jugadores en toda Cuba'],['Competición justa','Reglas claras y anti-toxicidad'],['Crecimiento constante','Proyectos y herramientas reales'],['Orgullo cubano','Unidos por Rainbow Six'],['100% apolítico','Solo juego, respeto y comunidad']],
    legal:'Rainbow Six CUBA es una comunidad independiente de fans y no está afiliada, asociada, autorizada ni respaldada por Ubisoft o Tom Clancy’s Rainbow Six Siege. Todo el contenido visual, nombres y referencias son ficticios y utilizados únicamente con fines de entretenimiento dentro del contexto gaming. Comunidad 100% apolítica.',
    footer:'Todos los derechos reservados.'
  },
  en: {
    nav:['Home','Community','Events','Competitive','Statistics','Coaches','Partners','Collaborators','Incoming'], badge:'Community operations center', title:['RAINBOW','SIX','CUBA'], subtitle:'The Cuban Rainbow Six Siege community.', body:'We coordinate players, teams, coaches and collaborators inside and outside Cuba to compete, organize and grow as a serious community.', join:'Join Discord', explore:'Explore Community', view:'View more', platform:'Community Platform', companion:'Companion Extension',
    modules:{community:['Community','Find players, teams and active Rainbow Six members inside and outside Cuba.'],events:['Events','Tournaments, scrims, cups and activities organized for the community.'],competitive:['Competitive','Teams, leagues, rankings and everything related to Cuban competitive play.'],statistics:['Statistics','Public statistics, leaderboards, analysis and player tracking.'],coaches:['Verified Coaches','Improve your game with community-verified coaches.'],partners:['Verified Partners','Organizations and communities supporting Rainbow Six growth in Cuba.'],collaborators:['Collaborators','People working behind the scenes to grow our community.'],incoming:['Incoming','New projects, tools and resources on the way.'],privacy:['Privacy','Protected data, transparency and clear rules for everyone.'],companion:['Companion Extension','The official Rainbow Six CUBA extension. Connect, analyze and take your experience to the next level.']},
    values:[['Active community','Players across Cuba and abroad'],['Fair competition','Clear rules and anti-toxicity'],['Constant growth','Real projects and tools'],['Cuban pride','United by Rainbow Six'],['100% apolitical','Only gaming, respect and community']], legal:'Rainbow Six CUBA is an independent fan community and is not affiliated, associated, authorized or endorsed by Ubisoft or Tom Clancy’s Rainbow Six Siege. All visual content, names and references are fictional and used only for entertainment within a gaming context. 100% apolitical community.', footer:'All rights reserved.'
  },
  fr: { nav:['Accueil','Communauté','Événements','Compétitif','Statistiques','Coachs','Partenaires','Collaborateurs','À venir'], badge:'Centre opérationnel communautaire', title:['RAINBOW','SIX','CUBA'], subtitle:'La communauté cubaine de Rainbow Six Siege.', body:'Nous coordonnons joueurs, équipes, coachs et collaborateurs pour grandir comme une communauté sérieuse.', join:'Rejoindre Discord', explore:'Découvrir la communauté', view:'Voir plus', platform:'Plateforme communautaire', companion:'Extension Companion', modules:{community:['Communauté','Joueurs, équipes et membres actifs de Rainbow Six.'],events:['Événements','Tournois, scrims et activités communautaires.'],competitive:['Compétitif','Équipes, ligues, classements et développement compétitif.'],statistics:['Statistiques','Statistiques publiques, classements et analyse.'],coaches:['Coachs vérifiés','Coachs validés par la communauté.'],partners:['Partenaires vérifiés','Organisations et communautés alliées.'],collaborators:['Collaborateurs','Personnes qui soutiennent la croissance de la communauté.'],incoming:['À venir','Nouveaux projets, outils et ressources.'],privacy:['Confidentialité','Données protégées et règles claires.'],companion:['Extension Companion','Outil officiel de Rainbow Six CUBA.']}, values:[['Communauté active','Joueurs connectés'],['Compétition juste','Règles claires'],['Croissance constante','Projets réels'],['Fierté cubaine','Unis par Rainbow Six'],['100% apolitique','Jeu, respect et communauté']], legal:'Rainbow Six CUBA est une communauté indépendante de fans, non affiliée à Ubisoft ou Tom Clancy’s Rainbow Six Siege. Tout contenu est fictif et destiné au divertissement gaming. Communauté 100% apolitique.', footer:'Tous droits réservés.' },
  de: { nav:['Start','Community','Events','Wettkampf','Statistiken','Coaches','Partner','Mitwirkende','Demnächst'], badge:'Community Operations Center', title:['RAINBOW','SIX','CUBA'], subtitle:'Die kubanische Rainbow Six Siege Community.', body:'Wir koordinieren Spieler, Teams, Coaches und Mitwirkende für Wachstum und Wettbewerb.', join:'Discord beitreten', explore:'Community ansehen', view:'Mehr', platform:'Community-Plattform', companion:'Companion-Erweiterung', modules:{community:['Community','Spieler, Teams und aktive Rainbow Six Mitglieder.'],events:['Events','Turniere, Scrims und Community-Aktivitäten.'],competitive:['Wettkampf','Teams, Ligen, Rankings und Wettbewerb.'],statistics:['Statistiken','Öffentliche Statistiken, Ranglisten und Analysen.'],coaches:['Verifizierte Coaches','Von der Community geprüfte Coaches.'],partners:['Verifizierte Partner','Organisationen und verbündete Communities.'],collaborators:['Mitwirkende','Menschen, die die Community unterstützen.'],incoming:['Demnächst','Neue Projekte, Tools und Ressourcen.'],privacy:['Datenschutz','Geschützte Daten und klare Regeln.'],companion:['Companion-Erweiterung','Offizielles Tool von Rainbow Six CUBA.']}, values:[['Aktive Community','Spieler weltweit'],['Faire Konkurrenz','Klare Regeln'],['Ständiges Wachstum','Reale Projekte'],['Kubanischer Stolz','Vereint durch Rainbow Six'],['100% apolitisch','Gaming, Respekt und Community']], legal:'Rainbow Six CUBA ist eine unabhängige Fan-Community und nicht mit Ubisoft oder Tom Clancy’s Rainbow Six Siege verbunden. Alle Inhalte sind fiktiv und dienen der Gaming-Unterhaltung. 100% apolitisch.', footer:'Alle Rechte vorbehalten.' },
  zh: { nav:['首页','社区','活动','竞技','统计','教练','伙伴','协作者','即将推出'], badge:'社区运营中心', title:['RAINBOW','SIX','CUBA'], subtitle:'古巴 Rainbow Six Siege 社区。', body:'我们连接古巴内外的玩家、队伍、教练与协作者，共同竞争与成长。', join:'加入 Discord', explore:'探索社区', view:'查看更多', platform:'社区平台', companion:'Companion 扩展', modules:{community:['社区','寻找玩家、队伍和活跃成员。'],events:['活动','锦标赛、训练赛和社区活动。'],competitive:['竞技','队伍、联赛、排行榜和竞技发展。'],statistics:['统计','公开统计、排行榜和分析。'],coaches:['认证教练','社区认证教练。'],partners:['认证伙伴','支持社区成长的组织。'],collaborators:['协作者','帮助社区成长的人。'],incoming:['即将推出','新项目、工具和资源。'],privacy:['隐私','数据保护和透明规则。'],companion:['Companion 扩展','Rainbow Six CUBA 官方工具。']}, values:[['活跃社区','玩家连接'],['公平竞争','清晰规则'],['持续成长','真实项目'],['古巴精神','因 Rainbow Six 团结'],['100% 非政治','游戏、尊重和社区']], legal:'Rainbow Six CUBA 是独立粉丝社区，与 Ubisoft 或 Tom Clancy’s Rainbow Six Siege 无关联。所有内容均为虚构，仅用于游戏娱乐。100% 非政治社区。', footer:'版权所有。' },
  ja: { nav:['ホーム','コミュニティ','イベント','競技','統計','コーチ','パートナー','協力者','近日公開'], badge:'コミュニティ作戦センター', title:['RAINBOW','SIX','CUBA'], subtitle:'キューバの Rainbow Six Siege コミュニティ。', body:'キューバ内外のプレイヤー、チーム、コーチ、協力者をつなぎます。', join:'Discord に参加', explore:'コミュニティを見る', view:'もっと見る', platform:'コミュニティプラットフォーム', companion:'Companion 拡張機能', modules:{community:['コミュニティ','プレイヤー、チーム、アクティブメンバーを探す。'],events:['イベント','大会、スクリム、コミュニティ活動。'],competitive:['競技','チーム、リーグ、ランキング、競技成長。'],statistics:['統計','公開統計、ランキング、分析。'],coaches:['認証コーチ','コミュニティ認証コーチ。'],partners:['認証パートナー','成長を支える組織。'],collaborators:['協力者','コミュニティを支える人々。'],incoming:['近日公開','新しいプロジェクト、ツール、リソース。'],privacy:['プライバシー','データ保護と明確なルール。'],companion:['Companion 拡張機能','Rainbow Six CUBA 公式ツール。']}, values:[['活発なコミュニティ','プレイヤーがつながる'],['公正な競争','明確なルール'],['継続的成長','実際のプロジェクト'],['キューバの誇り','Rainbow Six で団結'],['100% 非政治','ゲーム、尊重、コミュニティ']], legal:'Rainbow Six CUBA は独立したファンコミュニティで、Ubisoft または Tom Clancy’s Rainbow Six Siege とは関係ありません。内容は架空でゲーム娯楽目的のみです。100% 非政治的です。', footer:'無断転載を禁じます。' }
};

const moduleDefs = [
  ['community', Users, 'red', '/community.html', 'v12-community.webp'],
  ['events', CalendarDays, 'red', '/events.html', 'v12-events.webp'],
  ['competitive', Swords, 'gold', '/competitive.html', 'v12-competitive.webp'],
  ['statistics', BarChart3, 'blue', '/statistics.html', 'v12-statistics.webp'],
  ['coaches', GraduationCap, 'purple', '/coaches.html', 'v12-coaches.webp'],
  ['partners', BadgeCheck, 'green', '/partners.html', 'v12-partners.webp'],
  ['collaborators', HeartHandshake, 'red', '/collaborators.html', 'v12-collaborators.webp'],
  ['incoming', PackageOpen, 'orange', '/roadmap.html', 'v12-incoming.webp'],
  ['companion', Puzzle, 'blue wide', '/companion.html', 'v12-companion.webp'],
];

function initialLanguage(){const q=new URLSearchParams(location.search).get('lang');if(q&&DATA[q])return q;const s=localStorage.getItem(LANG_KEY);if(s&&DATA[s])return s;return 'es'}
function withLang(url, lang){if(!url||url.startsWith('http'))return url;return `${url}${url.includes('?')?'&':'?'}lang=${lang}`}
function useLang(){const [lang,setLang]=useState(initialLanguage);useEffect(()=>{localStorage.setItem(LANG_KEY,lang);document.documentElement.lang=lang;const u=new URL(location.href);if(u.searchParams.get('lang')!==lang){u.searchParams.set('lang',lang);history.replaceState({},'',u)}},[lang]);return [lang,setLang]}
function Logo({lang}){return <a className="brand" href={withLang('/',lang)}><span className="brand-mark">6</span><span><b>RAINBOW SIX</b><b>CUBA</b></span></a>}
function Header({t,lang,setLang}){const [open,setOpen]=useState(false);const paths=['/','/community.html','/events.html','/competitive.html','/statistics.html','/coaches.html','/partners.html','/collaborators.html','/roadmap.html'];return <header><Logo lang={lang}/><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{t.nav.map((n,i)=><a key={n} href={withLang(paths[i],lang)}>{n}</a>)}</nav><div className="head-actions"><label className="language"><Globe2 size={16}/><select value={lang} onChange={e=>setLang(e.target.value)}>{LANGUAGES.map(l=><option key={l.code} value={l.code}>{l.flag} {l.short}</option>)}</select></label><a className="discord" href={SITE_CONFIG.discord} target="_blank"><MessageCircle size={18}/>Discord</a></div></header>}
function Hero({t,lang}){return <section className="hero"><img className="hero-bg" src={`${IM}v12-hero-hq.webp`} alt="Rainbow Six CUBA headquarters"/><div className="hero-mask"/><aside className="side-rail"><span><Radio/>En vivo</span><span><Shield/>Partidos</span><span><BarChart3/>Stats</span><span><Users/>Social</span></aside><div className="hero-copy"><span className="eyebrow">{t.badge}</span><h1>{t.title.map((x,i)=><span key={x} className={i===2?'red':''}>{x}</span>)}</h1><h2>{t.subtitle}</h2><p>{t.body}</p><div className="ctas"><a className="btn primary" href={SITE_CONFIG.discord} target="_blank"><MessageCircle size={20}/>{t.join}</a><a className="btn ghost" href={withLang('/community.html',lang)}>{t.explore}<ChevronRight size={18}/></a></div></div></section>}
function Card({def,t,lang}){const [id,Icon,color,url,img]=def;const [title,text]=t.modules[id];return <a className={`module ${color}`} href={withLang(url,lang)}><img src={`${IM}${img}`} alt={title} loading="lazy"/><div className="modShade"/><div className="modText"><Icon className="modIcon" size={28}/><h3>{title}</h3><p>{text}</p><span>{t.view} <ChevronRight size={15}/></span></div></a>}
function Modules({t,lang}){return <section className="modules">{moduleDefs.map(d=><Card key={d[0]} def={d} t={t} lang={lang}/>)}</section>}
function Values({t}){const icons=[Users,Shield,TrendingUp,Flag,Ban];return <section className="values">{t.values.map(([a,b],i)=>{const I=icons[i]||Activity;return <div key={a}><I size={30}/><strong>{a}</strong><span>{b}</span></div>})}</section>}
function Notice({t,lang}){return <section className="notice"><LockKeyhole size={28}/><p>{t.legal}</p><Logo lang={lang}/></section>}
function Footer({t,lang}){return <footer><p>© 2026 Rainbow Six CUBA. {t.footer}</p><nav><a href={withLang('/privacy.html',lang)}>Privacidad</a><a href={withLang('/terms.html',lang)}>Términos</a><a href={withLang('/companion.html',lang)}>Companion</a><a href={withLang('/companion/support.html',lang)}>Soporte</a></nav></footer>}
function App(){const [lang,setLang]=useLang();const t=useMemo(()=>DATA[lang]||DATA.es,[lang]);return <><Header t={t} lang={lang} setLang={setLang}/><main><Hero t={t} lang={lang}/><Modules t={t} lang={lang}/><Values t={t}/><Notice t={t} lang={lang}/></main><Footer t={t} lang={lang}/></>}
createRoot(document.getElementById('root')).render(<App/>);
